version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/New_York"
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/New_York"
    cooldown:
      default-days: 7
