image: archlinux
packages:
  - nodejs
  - npm
  - jre-openjdk-headless
  - hut
oauth: pages.sr.ht/PAGES:RW
tasks:
  - build: |
      cd seven-guis
      npm install
      npm run build
  - package: |
      cd seven-guis
      tar -C public -cvz . > site.tar.gz
  - upload: |
      # Only upload on the main branch.
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi
      cd seven-guis
      hut pages publish -d seven-guis.vanburen.xyz site.tar.gz
