image: archlinux
packages:
  - nodejs
  - npm
  - jre-openjdk-headless
  - hut
oauth: pages.sr.ht/PAGES:RW
tasks:
  - build: |
      cd seven-guis
      npm install
      npm run build
  - upload: |
      cd seven-guis
      # Only upload on the main branch.
      if [ "$GIT_REF" != "refs/heads/main" ]
      then
        echo "Not on main branch, not publishing!"
        exit 0
      fi
      tar --directory public --create --gzip --verbose . > site.tar.gz
      hut pages publish --domain seven-guis.vanburen.xyz site.tar.gz
